kind: NamespaceSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: inference
spec:
  mode: dynamic
  selector:
    matchLabels: 
      fleet.gke.io/fleet-scope: team-llm
      kubernetes.io/metadata.name: inference