apiVersion: v1
metadata:
  name: asm-options
  namespace: istio-system
data:
  multicluster_mode: connected
  mesh: |-
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    defaultConfig:
      tracing:
        stackdriver: {}
kind: ConfigMap