availableSecrets:
  secretManager:
  - versionName: projects/927114482793/secrets/ALBERTWO1978-GH-TOKEN/versions/latest
    env: GH_TOKEN

steps:
- name: 'alpine'
  id: 'branch name'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

# [START tf-fmt]
- name: 'hashicorp/terraform:0.13.0'
  id: 'tf fmt'  
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "terraform/" ]; then
        for dir in terraform/*
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}  
          echo ""
          echo "*************** TERRAFOM FMT ******************"
          echo "******* At environment: ${env} ********"
          echo "***********************************************"

          terraform fmt -diff -check=true -write=false
          if [ $? -ne 0 ]; then
            apk add curl
            echo "{\"body\": \"Please run the \`terraform fmt\` command against /terraform/${env} directory the resubmit the Pull Request. It is required that \`terraform fmt\` be executed against all Terraform configuration files in order to provide a consistent canonical format and style.\"}" > /workspace/api_payload.txt && \
            curl -s -H "Authorization: token $$GH_TOKEN" -X POST -d @/workspace/api_payload.txt "https://api.github.com/repos/albertwo1978/gke-poc-toolkit-1/issues/$_PR_NUMBER/comments"
            exit 1
          fi
          cd ../../
        done
      fi 
  secretEnv: ['GH_TOKEN']
# [END tf-fmt]

# [END tf-init]
- name: 'hashicorp/terraform:0.13.0'
  id: 'tf init'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "terraform/" ]; then
        for dir in terraform/*
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd ../../
        done
      fi 
# [END tf-init]

# [START tf-plan]
- name: 'hashicorp/terraform:0.13.0'
  id: 'tf plan'  
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "terraform/" ]; then
        for dir in terraform/*
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}  
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "************************************************"

          # Changing bastion members to GKE Service Account Email for validation purposes.
          sed -i s/data.google_client_openid_userinfo.me.email/local.gke_service_account_email/g main.tf

          # Remove workloads.tf for testing purposes - requires an existing deployment. 
          if [ -f "workload.tf" ]; then
            rm workload.tf
          fi

          # Remove provider.tf for testing purposes - requires an existing deployment. 
          if [ -f "provider.tf" ]; then
            rm provider.tf
          fi

          terraform plan || exit 1
          cd ../../
        done
      fi 
# [END tf-plan]