apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: workload-id-demo-gsa
spec:
  displayName: workload-id-demo-sa
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
  name: gke-application-bucket-a951a5
  namespace: workload-id-demo
spec:
  bucketPolicyOnly: true
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: workload-id-demo-storage-policy
  namespace: workload-id-demo
spec:
  member: serviceAccount:workload-id-demo-gsa@gke-toolkit-test-11.iam.gserviceaccount.com
  role: roles/storage.objectAdmin
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    external: gke-application-bucket-a951a5 
