project_id                        = "<no value>"
governance_project_id             = "my-awesome-project
"
region                            = "us-central1"
private_endpoint                  = "Standard"
cluster_name                      = "Standard-endpoint-cluster"
vpc_name                          = "Standard-cluster-network"
subnet_name                       = "Standard-cluster-subnet"
node_pool                         = "Standard-node-pool"
zone                              = "us-central1-b"
auth_ip                           = ""
windows_nodepool                  = "false"
preemptible_nodes                 = "false"
shared_vpc                        = ""
shared_vpc_name                   = "default"
shared_vpc_subnet_name            = "default"
shared_vpc_project_id             = "my-awesome-project
"
shared_vpc_ip_range_pods_name     = ""
shared_vpc_ip_range_services_name = ""