apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: default-httproute
  namespace: asm-gateways
  annotations:
    configsync.gke.io/cluster-name-selector: gke-dev-us-central1-01
spec:
  parentRefs:
  - name: external-http
    namespace: asm-gateways
    sectionName: https
  rules:
  - backendRefs:
    - group: net.gke.io
      kind: ServiceImport
      name: asm-ingress-gateway-xlb
      port: 443
