apiVersion: v1
kind: Namespace
metadata:
  name: buffer
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacity-res-deploy
  namespace: buffer
spec:
  replicas: 10
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      priorityClassName: low-priority
      terminationGracePeriodSeconds: 0
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        resources:
          requests:
            cpu: 2000m
            memory: 4000Mi