apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: custom:aggregate-to-edit:gateway
rules:
- apiGroups:
  - "net.gke.io"
  - "gateway.networking.k8s.io"
  resources:
  - "*"
  verbs:
  - "*"