apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: custom:aggregate-to-edit:monitoring
rules:
- apiGroups:
  - "monitoring.googleapis.com"
  resources:
  - "*"
  verbs:
  - "*"