apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: app-secrets
  namespace: workload-id-demo
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/1045984487745/secrets/testsecret/versions/latest"
        fileName: "good1.txt"