apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: 
    iam.gke.io/gcp-service-account: csi-demo-gsa@gke-toolkit-test-11.iam.gserviceaccount.com
  name: csi-demo-ksa
  namespace: workload-id-demo
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: csi-demo-gsa
spec:
  displayName: csi-demo-gsa
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: csi-demo-sa-policy
  namespace: workload-id-demo
spec:
  resourceRef:
    apiVersion:  iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: csi-demo-gsa
  bindings:
    - role: roles/iam.workloadIdentityUser 
      members: 
        - serviceAccount:gke-toolkit-test-11.svc.id.goog[workload-id-demo/workload-id-demo-ksa]
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: csi-demo-policy
  namespace: workload-id-demo
spec:
  member: serviceAccount:csi-demo-gsa@gke-toolkit-test-11.iam.gserviceaccount.com
  role: roles/secretmanager.secretAccessor
  resourceRef:
    apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
    kind: SecretManagerSecret
    external: testsecret               
