swagger: "2.0"
info:
  description: "Cloud Endpoints DNS"
  title: "Cloud Endpoints DNS"
  version: "1.0.0"
paths: {}
host: "welcome.endpoints.${PROJECT_ID}.cloud.goog"
x-google-endpoints:
- name: "welcome.endpoints.${PROJECT_ID}.cloud.goog"
  target: "${WELCOME_IP}"