apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-reader-service-account-clusterrolebinding
  labels:
    app: istio-reader
    release: istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-reader-service-account-clusterrole
subjects:
  - kind: ServiceAccount
    name: istio-reader-service-account
    namespace: istio-system